apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  sources:
    # Primary source: your Git repo
    - repoURL: https://github.com/dmestresequeira/ArgoCD.git
      targetRevision: main
      path: ingress/traefik
      helm:
        releaseName: traefik-traefik-system
        valueFiles:
          - values.yaml

    # Secondary source: the Traefik Helm chart
    - repoURL: https://helm.traefik.io/traefik
      chart: traefik
      targetRevision: 28.0.0

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
