apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  sources:
    # Source 1: Your Git repo containing values.yaml
    - repoURL: https://github.com/dmestresequeira/ArgoCD.git
      targetRevision: main
      ref: values
    # Source 2: Traefik Helm chart
    - repoURL: https://helm.traefik.io/traefik
      chart: traefik
      targetRevision: 28.0.0
      helm:
        releaseName: traefik
        valueFiles:
          - $values/ingress/traefik/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
